### ISSUE TITLE
Include $BCH, #BCH and #BitcoinCash for related crypto list of phrases

### ISSUE THREAD

**Issue by RowanSkie** [antsstyle/nftcryptoblocker#2]
Anyway, as a BCHer, I noticed the list of [blockable phrases](https://antsstyle.com/nftcryptoblocker/blockablephrases) and noticed that my crypto of choice (which I use as money and a few groups are using it for their NFT shenanigans) isn't added. 

So, yeah, Bitcoin Cash apparently not on the list. Heh.

EDIT: Before anyone calls hypocrisy, this app is actually good for Twitter since it's one less toxic community to go to. And, uh, besides, it's kinda unfair since BCH is actually building a lot that will affect a lot soon, and probably not in the way of "money go up" or the shitty NFTs these days.

**Comment by antsstyle** [comment]
Thank you for informing me, I shall add it in!

**Comment by RowanSkie** [comment]
Nice! Noticed it's added in now. Thanks for adding my suggestion (or issue). I'll close this now. ^-^
