### ISSUE TITLE
Twitter sign in is broken

### ISSUE THREAD

**Issue by clepdn** [antsstyle/nftcryptoblocker#5]
iOS 15.3.1 iphone 12 pro, safari

![29DFA9D5-4552-47E0-A443-877246CAE15A](https://user-images.githubusercontent.com/25444923/157046675-e92cf9cf-50b9-4fc5-8536-65b6ffe031af.png)

**Comment by antsstyle** [comment]
Unfortunately this is a more serious problem than I expected - Twitter has suspended the app and not told me (they supposedly send an email when this happens, but I haven't received one).

I've sent in a support ticket and will talk to them on the forums as well. Will update this when I hear changes, but for now, there's little to be done - the app is effectively offline until it's resolved.
